### ISSUE TITLE
Add Screenshots and Update README

### ISSUE THREAD

**Issue by RewoundVHS** [NerdyPepper/curie#3]
This font is really beautiful, why not showcase it before the user decides to download? I could help with this if you would like another contributor.

**Comment by NerdyPepper** [comment]
Sure!

I have added you as a collaborator. Just make sure to host the images and link them in the readme.

**Comment by topisani** [comment]
Could you maybe add screenshots of bold/italic versions as well? would be nice to have with the same colorscheme

**Comment by RewoundVHS** [comment]
Sure, I will as soon as possible!

**Comment by RewoundVHS** [comment]
I have added a screenshot including the bold and italic variants
