### ISSUE TITLE
Fix installation instructions?

### ISSUE THREAD

**Issue by Anachron** [NerdyPepper/curie#5]
sudo rm /etc/fonts/conf.d/10* && sudo rm -rf 70-no-bitmaps.conf

I supposed its meant to be „sudo cd“ on the first command? Or why would you delete everything with 10* in that directory? You never know what the user has written in there!

**Comment by NerdyPepper** [comment]
I copied the instructions from [here](https://wiki.ubuntu.com/Fonts).

I believe those files are responsible for disabling bitmap fonts on ubuntu / debian based distros.

**Comment by Anachron** [comment]
Please take another look. One command deletes by an absolute path, the next one relative. How can the relative deletion work?

Something must be wrong with the instructions.

**Comment by NerdyPepper** [comment]
Oh I see my mistake! I will fix up the README asap. Sorry for the confusion!
