### ISSUE TITLE
Add layout glyphs

### ISSUE THREAD

**Issue by Sacules** [NerdyPepper/curie#7]
Siji has several of them:

![Imgur](https://i.imgur.com/HwjUC4P.png)

- Monocle (U+E001)
- Tiling (U+E002)
- Bottom Stack (U+E003)
- Bottom Stack Horizontal (U+E004)
- Floating (U+E006) 
- Fibonacci (U+E007)

Using siji along with curie doesn't work well since they have different sizes and end up misaligned, so incorporating these would be more appropiate :)

**Comment by NerdyPepper** [comment]
Curie's bounding box is not big enough to fit these high detail characters.
